---
PlayerShip[testship]:
    max_hp: 100
    imagepath: ships/test_ship.png
    engine_glow_imagepath: ships/test_ship_engine_glow.png
    acceleration: 2000
    max_speed: 500
    weapons:
      - Weapon(testgun)
EnemyShip[testenemyship]:
    max_hp: 10
    imagepath: ships/test_ship.png
    acceleration: 1000
    max_speed: 200
    weapons:
      - Weapon(enemygun)
    move_behavior:
      Patrol[back_and_forth]:
        dests:
          - [0.75, 0.25]
          - [0.25, 0.25]
    fire_behavior:
      FireConstantly[fire_constantly]: {}
