---
PlayerShip[t_wing]:
    max_hp: 10
    imagepath: ships/t_wing.png
    engine_glow_imagepath: ships/t_wing_engine_glow.png
    acceleration: 800
    max_speed: 300
    weapons:
      - Weapon(blaster_cannon)
    shield: Shield(testshield)
PlayerShip[testship]:
    max_hp: 10
    imagepath: ships/t_wing.png
    engine_glow_imagepath: ships/t_wing_engine_glow.png
    acceleration: 2000
    max_speed: 500
    weapons:
      - Weapon(homing_hose)
    shield: Shield(testshield)
EnemyShip[testenemyship]:
    max_hp: 10
    imagepath: ships/wedge.png
    acceleration: 1000
    max_speed: 200
    weapons:
      - Weapon(enemygun)
    move_behavior:
      FixedPatrol(back_and_forth)
    fire_behavior:
      FireAtPlayer(fire_at_player)
EnemyShip[invader_green]:
    max_hp: 1
    imagepath: ships/invader_green.png
    acceleration: 1000
    max_speed: 150
    enable_small_health_bar: false
    weapons:
      - Weapon(green_laser)
    move_behavior:
      FixedPatrol(back_and_forth)
    fire_behavior:
      FireConstantly(fire_constantly)
EnemyShip[invader_red]:
    max_hp: 1
    imagepath: ships/invader_red.png
    acceleration: 1000
    max_speed: 150
    enable_small_health_bar: false
    weapons:
      - Weapon(red_laser)
    move_behavior:
      FixedPatrol(back_and_forth)
    fire_behavior:
      FireConstantly(fire_constantly)
EnemyShip[invader_blue]:
    max_hp: 1
    imagepath: ships/invader_blue.png
    acceleration: 1000
    max_speed: 150
    enable_small_health_bar: false
    weapons:
      - Weapon(blue_laser)
    move_behavior:
      FixedPatrol(back_and_forth)
    fire_behavior:
      FireConstantly(fire_constantly)
