---
PlayerShip[testship]:
    imagepath: ships/test_ship.png
    engine_glow_imagepath: ships/test_ship_engine_glow.png
    acceleration: 2000
    max_speed: 500
    weapons:
      - Weapon(testgun)
EnemyShip[testenemyship]:
    imagepath: ships/test_ship.png
    acceleration: 1000
    max_speed: 200
    weapons:
      - Weapon(testgun)
    move_behavior:
      Patrol[back_and_forth]:
        dests:
          - [0.75, 0.25]
          - [0.25, 0.25]
