---
PlayerShip[testship]:
    max_hp: 100
    imagepath: ships/t_wing.png
    engine_glow_imagepath: ships/t_wing_engine_glow.png
    acceleration: 2000
    max_speed: 500
    weapons:
      - Weapon(homing_gun)
    shield: Shield(testshield)
EnemyShip[testenemyship]:
    max_hp: 10
    imagepath: ships/wedge.png
    acceleration: 1000
    max_speed: 200
    weapons:
      - Weapon(enemygun)
    move_behavior:
      Patrol(back_and_forth)
    fire_behavior:
      FireAtPlayer(fire_at_player)
