---
Weapon[testgun]:
    rate_of_fire: 4.0
    projectiles:
      - Projectile(testproj):
          angle: -15
      - Projectile(testproj):
          angle: 0
      - Projectile(testproj):
          angle: 15