---
Weapon[testgun]:
  rate_of_fire: 4.0
  projectiles:
    - Projectile(testproj):
        angle: -60
    - Projectile(testproj):
        angle: 0
    - Projectile(testproj):
        angle: 60
Weapon[homing_gun]:
  rate_of_fire: 10.0
  projectiles:
    - Projectile(homing_proj)
Weapon[enemygun]:
  rate_of_fire: 0.5
  projectiles:
    - Projectile(testproj)
Weapon[slowgun]:
  rate_of_fire: 0.125
  projectiles:
    - Projectile(testproj):
        speed: 10
        relative_to_firer_velocity: false
        damage: 6
