---
Weapon[testgun]:
  rate_of_fire: 4.0
  projectiles:
    - Projectile(testproj):
        angle: -60
    - Projectile(testproj):
        angle: 0
    - Projectile(testproj):
        angle: 60
Weapon[homing_gun]:
  rate_of_fire: 2.0
  projectiles:
    - Projectile(homing_proj)
Weapon[enemygun]:
  rate_of_fire: 0.5
  projectiles:
    - Projectile(testproj)
