---
Level[level1]:
  name: 'Level 1: The Testening'
  shop_items:
    - Weapon(testgun)
    - Weapon(yondus_arrow)
    - Weapon(mind_control_gun)
    - Shield(testshield)
  waves:
    - condition:
        AlwaysTrue():
          delay: 1.0
      formations:
        - Line(wave1)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Line(wave2)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Grid(wave3)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Grid(wave4)
