---
Level[testlevel]:
  name: 'Level 1: The Testening'
  shop_items:
    - Weapon(testgun)
    - Weapon(yondus_arrow)
    - Weapon(mind_control_gun)
    - Shield(testshield)
  waves:
    - condition:
        AlwaysTrue():
          delay: 1.0
      formations:
        - Line(enemy_line)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Line(enemy_followers)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Grid(invader_grid)
    - condition:
        LastWaveDefeated():
          delay: 1.0
      formations:
        - Grid(invader_grid)
Level[level1]:
  name: 'Level 1: The Real Testening'
  shop_items:
    - Weapon(blaster_cannon)
    - Weapon(dual_blaster_cannon)
    - Weapon(triple_blaster_cannon)
    - Weapon(rapid_blaster_cannon)
    - Shield(testshield)
  waves:
    - condition:
        AlwaysTrue():
          delay: 1.0
      formations:
        - Line(invader_line):
            dest_y: 40
    # - condition:
    #     LastWaveDefeated():
    #       delay: 1.0
    #   formations:
    #     - Line(wave2)
    # - condition:
    #     LastWaveDefeated():
    #       delay: 1.0
    #   formations:
    #     - Grid(wave3)
    # - condition:
    #     LastWaveDefeated():
    #       delay: 1.0
    #   formations:
    #     - Grid(wave4)

