---
Level[level1]:
  waves:
    - condition: null
      formations:
        - Line(wave1)
    - condition:
        LastWaveDefeated():
          delay: 5.0
      formations:
        - Line(wave2)
    - condition:
        LastWaveDefeated()
      formations:
        - Grid(wave3)
