---
MoveBehavior[move_on_screen]:
  initial_dest: [0.5, 0.25]
Idle[idle]:
  a: 1
FixedPatrol[back_and_forth]:
  dests:
    - [0.25, 0.25]
    - [0.75, 0.25]
  pause_time: 2
Homing[basic_homing]:
  test: 1
RandomPatrol[around]:
  width: 0.5
  height: 0.5
