---
Projectile[testproj]:
  imagepath: projectiles/blue_blast.png
  speed: 500
  damage: 1
Projectile[green_beam]:
  imagepath: projectiles/green_beam.png
  speed: 400
  damage: 1
  relative_to_firer_velocity: false
Projectile[red_beam]:
  imagepath: projectiles/red_beam.png
  speed: 400
  damage: 2
  relative_to_firer_velocity: false
Projectile[blue_beam]:
  imagepath: projectiles/blue_beam.png
  speed: 400
  damage: 1
  relative_to_firer_velocity: false
Projectile[homing_proj]:
  imagepath: projectiles/blue_blast.png
  speed: 300
  acceleration: 500
  max_speed: 300
  damage: 2
  move_behavior: Homing(basic_homing)
  fuel_duration: 3
  piercing: 1
Projectile[mind_control_proj]:
  imagepath: projectiles/purple_blast.png
  speed: 300
  acceleration: 500
  max_speed: 300
  damage: 0
  move_behavior: Homing(basic_homing)
  fuel_duration: 10
  piercing: 1
  effects:
    - MindControl(mind_control):
        duration: 4
    - AddVFX():
        duration: 4
        vfx:
          CircleVFX():
            above: true
            color: [64, 64, 255]
            alpha: 80
BehaviorAlteringProjectile[stop_firing_proj]:
  imagepath: projectiles/purple_blast.png
  speed: 300
  acceleration: 500
  max_speed: 300
  damage: 1
  move_behavior: Homing(basic_homing)
  fuel_duration: 3
  fire_behavior_to_apply: FireNever(fire_never)
  effect_duration: 5
