---
  Projectile[testproj]:
    imagepath: projectiles/test_projectile.png
    speed: 500
    damage: 1
  Projectile[homing_proj]:
    imagepath: projectiles/test_projectile.png
    speed: 300
    acceleration: 500
    max_speed: 300
    damage: 2
    move_behavior: Homing(basic_homing)
