---
Projectile[testproj]:
  imagepath: projectiles/blue_blast.png
  speed: 500
  damage: 1

Projectile[homing_proj]:
  imagepath: projectiles/blue_blast.png
  speed: 300
  acceleration: 500
  max_speed: 300
  damage: 2
  move_behavior: Homing(basic_homing)
  fuel_duration: 3
